In [ ]:
import pandas as pd

# Load your dataset
df = pd.read_csv('/contentransomwaredata.csv')

# Display the first few rows of the dataset to understand its structure
print(df.head())


   __exception__      bind  certopenstore  closesocket  cocreateinstance  \
0      -0.131260  0.248462      -0.125446    -0.015558         -0.178703   
1      -0.131157  0.248436      -0.125337    -0.015250         -0.178786   
2      -0.127825  0.243793      -0.125039    -0.012303         -0.176607   
3      -0.131869  0.249265      -0.125554    -0.016186         -0.179052   
4      -0.124988  0.239836      -0.124926    -0.009866         -0.174819   

   cocreateinstanceex  cogetclassobject  coinitializeex  coinitializesecurity  \
0            0.105346          0.201149        0.141872              0.167527   
1            0.105290          0.201207        0.141893              0.167763   
2            0.104306          0.198937        0.137156              0.164229   
3            0.105526          0.201514        0.142686              0.168038   
4            0.103391          0.196995        0.133231              0.161176   

    connect  ...   wsarecv  wsarecvfrom  wsasendto  wsas

In [ ]:
# prompt: dataset features

# Get the list of column names (features)
features = df.columns.tolist()

# Print the features
print("Dataset Features:")
for feature in features:
  print(feature)


Dataset Features:
__exception__
bind
certopenstore
closesocket
cocreateinstance
cocreateinstanceex
cogetclassobject
coinitializeex
coinitializesecurity
connect
controlservice
copyfilea
copyfileexw
copyfilew
couninitialize
createactctxw
createdirectoryw
createprocessinternalw
createremotethread
createservicea
createservicew
createthread
createtoolhelp32snapshot
deletefilew
deleteservice
deleteurlcacheentrya
deviceiocontrol
dnsquery_a
dnsquery_w
drawtextexa
drawtextexw
enumservicesstatusa
enumwindows
findfirstfileexw
findresourcea
findresourceexa
findresourceexw
findresourcew
findwindowa
findwindowexa
findwindowexw
findwindoww
getadaptersaddresses
getadaptersinfo
getaddrinfo
getasynckeystate
getcomputernamea
getcomputernamew
getcursorpos
getdiskfreespaceexw
getdiskfreespacew
getfileattributesexw
getfileattributesw
getfileinformationbyhandle
getfilesize
getfilesizeex
getfiletype
getfileversioninfosizew
getfileversioninfow
getforegroundwindow
gethostbyname
getinterfaceinfo
getkeyboardstate

In [ ]:
# Check for null values
print(df.isnull().sum())

# Drop rows or columns with missing values (if needed)
df.dropna(inplace=True)

# Check the column names
print(df.columns)


__exception__       0
bind                0
certopenstore       0
closesocket         0
cocreateinstance    0
                   ..
wsastartup          0
getaddrinfow        0
thread32first       0
thread32next        0
Label               0
Length: 247, dtype: int64
Index(['__exception__', 'bind', 'certopenstore', 'closesocket',
       'cocreateinstance', 'cocreateinstanceex', 'cogetclassobject',
       'coinitializeex', 'coinitializesecurity', 'connect',
       ...
       'wsarecv', 'wsarecvfrom', 'wsasendto', 'wsasocketa', 'wsasocketw',
       'wsastartup', 'getaddrinfow', 'thread32first', 'thread32next', 'Label'],
      dtype='object', length=247)


In [ ]:
# Define features and target
X = df.drop(columns=['bind'])  # Replace 'label' with your actual target column name
y = df['bind']  # Replace 'label' with your actual target column name


In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Split the dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Normalize the features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)


In [ ]:
# Convert the target variable 'bind' to discrete values if it's continuous
# For example, you can use binning:

# Assuming 'bind' is between 0 and 1
bind = [0, 0.5, 1]  # Define your bins
certopenstore = [0, 1]     # Define your labels

y_train = pd.cut(y_train, bins=bins, labels=labels, include_lowest=True)
y_test = pd.cut(y_test, bins=bins, labels=labels, include_lowest=True)

# Now, you can use the classification models

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

# Example dataset
df = pd.read_csv('/content/RW data1.csv')

# Convert continuous target to categorical (e.g., binary classification)
# For demonstration, we assume 'label' is continuous and convert it to binary
# You can use different binning strategies based on your dataset
threshold_value = df['certopenstore'].mean()  # Adjust this threshold as needed - using the mean for a better split
df['bind'] = np.where(df['certopenstore'] > threshold_value, 1, 0)  # Replace threshold_value with appropriate value and ensure distinct classes (0 and 1)

# Prepare features and target
X = df.drop(columns=['bind'])
y = df['bind']

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Normalize the features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# 1. Random Forest Classifier
rf = RandomForestClassifier(n_estimators=100, random_state=42)
rf.fit(X_train, y_train)
y_pred_rf = rf.predict(X_test)

print("Random Forest Classifier Results:")
print(confusion_matrix(y_test, y_pred_rf))
print(classification_report(y_test, y_pred_rf))
print(f"Accuracy: {accuracy_score(y_test, y_pred_rf)}")

# 2. Support Vector Machine (SVM)
svm = SVC(kernel='linear', random_state=42)
svm.fit(X_train, y_train)
y_pred_svm = svm.predict(X_test)

print("Support Vector Machine Results:")
print(confusion_matrix(y_test, y_pred_svm))
print(classification_report(y_test, y_pred_svm))
print(f"Accuracy: {accuracy_score(y_test, y_pred_svm)}")

# 3. Gradient Boosting Classifier
gb = GradientBoostingClassifier(n_estimators=100, random_state=42)
gb.fit(X_train, y_train)
y_pred_gb = gb.predict(X_test)

print("Gradient Boosting Classifier Results:")
print(confusion_matrix(y_test, y_pred_gb))
print(classification_report(y_test, y_pred_gb))
print(f"Accuracy: {accuracy_score(y_test, y_pred_gb)}")

Random Forest Classifier Results:
[[208   0]
 [  2 215]]
              precision    recall  f1-score   support

           0       0.99      1.00      1.00       208
           1       1.00      0.99      1.00       217

    accuracy                           1.00       425
   macro avg       1.00      1.00      1.00       425
weighted avg       1.00      1.00      1.00       425

Accuracy: 0.9952941176470588
Support Vector Machine Results:
[[208   0]
 [  0 217]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       208
           1       1.00      1.00      1.00       217

    accuracy                           1.00       425
   macro avg       1.00      1.00      1.00       425
weighted avg       1.00      1.00      1.00       425

Accuracy: 1.0
Gradient Boosting Classifier Results:
[[208   0]
 [  0 217]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       208
           1       1.

In [ ]:
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.svm import SVR
from sklearn.metrics import mean_squared_error, r2_score

# Example dataset
df = pd.read_csv('/content/RW data1.csv')

# Prepare features and target
X = df.drop(columns=['bind'])
y = df['bind']

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Normalize the features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# 1. Random Forest Regressor
rf = RandomForestRegressor(n_estimators=100, random_state=42)
rf.fit(X_train, y_train)
y_pred_rf = rf.predict(X_test)

print("Random Forest Regressor Results:")
print(f"Mean Squared Error: {mean_squared_error(y_test, y_pred_rf)}")
print(f"R^2 Score: {r2_score(y_test, y_pred_rf)}")

# 2. Support Vector Regressor (SVR)
svr = SVR(kernel='linear')
svr.fit(X_train, y_train)
y_pred_svr = svr.predict(X_test)

print("Support Vector Regressor Results:")
print(f"Mean Squared Error: {mean_squared_error(y_test, y_pred_svr)}")
print(f"R^2 Score: {r2_score(y_test, y_pred_svr)}")

# 3. Gradient Boosting Regressor
gb = GradientBoostingRegressor(n_estimators=100, random_state=42)
gb.fit(X_train, y_train)
y_pred_gb = gb.predict(X_test)

print("Gradient Boosting Regressor Results:")
print(f"Mean Squared Error: {mean_squared_error(y_test, y_pred_gb)}")
print(f"R^2 Score: {r2_score(y_test, y_pred_gb)}")


Random Forest Regressor Results:
Mean Squared Error: 3.721635318428624e-09
R^2 Score: 0.999868449933476
Support Vector Regressor Results:
Mean Squared Error: 2.916490740975243e-05
R^2 Score: -0.030903133071623845
Gradient Boosting Regressor Results:
Mean Squared Error: 7.74124225613564e-09
R^2 Score: 0.9997263673501995


In [ ]:
# identify the ransomware features

import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# Load your dataset
df = pd.read_csv('/content/RW data1.csv')

# Assuming 'bind' is your target variable (indicating ransomware or not)
X = df.drop('bind', axis=1)
y = df['bind']

# Convert 'bind' to discrete values (if necessary)
# Here's an example using a threshold to create a binary classification problem
threshold = y.mean()  # Example threshold - adjust as needed
y = (y > threshold).astype(int)

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train a Random Forest Classifier (you can use other models as well)
model = RandomForestClassifier()
model.fit(X_train, y_train)

# Get feature importances
feature_importances = pd.Series(model.feature_importances_, index=X.columns)

# Sort features by importance in descending order
feature_importances = feature_importances.sort_values(ascending=False)

# Print the top N most important features
print("Top 10 Most Important Features for Ransomware Identification:")
print(feature_importances.head(10))

# You can analyze the top features to understand which ones are most relevant for ransomware detection.
# For example, you might find that features related to network activity, file access patterns, or process creation are highly important.

Top 10 Most Important Features for Ransomware Identification:
ldrgetdllhandle                      0.070000
getfilesizeex                        0.050164
createservicea                       0.050117
regcreatekeyexw                      0.050070
lookupaccountsidw                    0.050070
sendnotifymessagea                   0.049953
getvolumenameforvolumemountpointw    0.040024
ntopenfile                           0.039953
process32firstw                      0.039930
rtladdvectoredexceptionhandler       0.030211
dtype: float64


In [ ]:
# prompt: analyze why they are important

# Load your dataset
df = pd.read_csv('/content/RW data1.csv')

# Assuming 'bind' is your target variable (indicating ransomware or not)
X = df.drop('bind', axis=1)
y = df['bind']

# Convert 'bind' to discrete values (if necessary)
# Here's an example using a threshold to create a binary classification problem
threshold = y.mean()  # Example threshold - adjust as needed
y = (y > threshold).astype(int)

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train a Random Forest Classifier (you can use other models as well)
model = RandomForestClassifier()
model.fit(X_train, y_train)

# Get feature importances
feature_importances = pd.Series(model.feature_importances_, index=X.columns)

# Sort features by importance in descending order
feature_importances = feature_importances.sort_values(ascending=False)

# Print the top N most important features
print("Top 10 Most Important Features for Ransomware Identification:")
print(feature_importances.head(10))


# Analyze the importance of the top features
print("\nAnalysis of Top Features:")
for feature, importance in feature_importances.head(10).items():
  print(f"- {feature}:")
  if feature == 'certopenstore':
    print("  - This feature might represent the number of files opened or created during ransomware execution. ")
    print("  - Ransomware often creates or opens files to encrypt or modify data.")
  elif feature == 'certopen':
    print("  - This feature might represent the number of files opened or created during ransomware execution.")
    print("  - Ransomware often creates or opens files to encrypt or modify data.")
  elif feature == 'certopen':
    print("  - This feature might represent the number of files opened or created during ransomware execution.")
    print("  - Ransomware often creates or opens files to encrypt or modify data.")
  elif feature == 'certopen':
    print("  - This feature might represent the number of files opened or created during ransomware execution.")
    print("  - Ransomware often creates or opens files to encrypt or modify data.")
  elif feature == 'certopen':
    print("  - This feature might represent the number of files opened or created during ransomware execution.")
    print("  - Ransomware often creates or opens files to encrypt or modify data.")

  # Add more analysis for other features as needed
  print(f"  - Importance: {importance:.3f}")


Top 10 Most Important Features for Ransomware Identification:
getfileversioninfow                  0.080047
regcreatekeyexw                      0.060047
getfilesizeex                        0.050070
getcomputernamea                     0.050000
createservicea                       0.050000
getsystemmetrics                     0.049836
ntsavekey                            0.040233
getvolumenameforvolumemountpointw    0.040000
lookupprivilegevaluew                0.039789
shgetspecialfolderlocation           0.030234
dtype: float64

Analysis of Top Features:
- getfileversioninfow:
  - Importance: 0.080
- regcreatekeyexw:
  - Importance: 0.060
- getfilesizeex:
  - Importance: 0.050
- getcomputernamea:
  - Importance: 0.050
- createservicea:
  - Importance: 0.050
- getsystemmetrics:
  - Importance: 0.050
- ntsavekey:
  - Importance: 0.040
- getvolumenameforvolumemountpointw:
  - Importance: 0.040
- lookupprivilegevaluew:
  - Importance: 0.040
- shgetspecialfolderlocation:
  - Importance: 